### PR TITLE
Add Steam and application icons

### PR DESCRIPTION
**Pull request by Masterkatze**
## Description
Add Steam and application icons:

Steam library:
steam_library

Windows taskbar:
taskbar

Linux KDE task panel:
taskbar_linux_kde

Desktop .url shortcut doesn't show an icon - I think it tries to use the (missing) steamdb one.

Also refactored gameinfo.txt a little - removed comments because it's just a copy from [here](https://developer.valvesoftware.com/wiki/Gameinfo.txt).

## Toolchain
- Windows MSVC VS2022

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
Could you change the title in gameinfo.txt to "neatbkyoc ue"?

**Comment by AdamTadeusz** [comment]
Are all those changes in gameinfo.txt necessary to get the icons working?

**Comment by Masterkatze** [comment]
> Could you change the title in gameinfo.txt to "neatbkyoc ue"?

Sure (btw what does these titles mean?)

> Are all those changes in gameinfo.txt necessary to get the icons working?

Only the `Icon "resource/icon"` one, but I took a chance to tidy the whole file according to the documentation.

**Comment by AdamTadeusz** [comment]
> > Could you change the title in gameinfo.txt to "neatbkyoc ue"?
> 
> Sure (btw what does these titles mean?)
> 
> > Are all those changes in gameinfo.txt necessary to get the icons working?
> 
> Only the `Icon "resource/icon"` one, but I took a chance to tidy the whole file according to the documentation.

https://github.com/NeotokyoRebuild/neo/pull/526

https://developer.valvesoftware.com/wiki/Gameinfo.txt For other reviewers. Looks fine to me

**Review by AdamTadeusz — DISMISSED** [review]

**Review by AdamTadeusz — APPROVED** [review]

**Pull request merged**
