### PR TITLE
Original central messages

### LINKED ISSUE #454: The center text messages should match OG NT
### Build Info

20240629_321f139

### Description

Center text messages like GO GO GO don't match the OG NT style.

### To Reproduce

Play a match and observe the center text messages on round start.

### Expected behavior

Some strings lifted from the OG binaries:
```
- VIP ROUND %s1 STARTED -
- NEW ROUND START DELAYED - ONE OR BOTH TEAMS HAS NO PLAYERS -
- CTG ROUND %s1 STARTED -
- ROUND %s1 STARTED -
- GO! GO! GO! -
```

### Actual behavior

The messages are less verbose or are missing the surrounding hyphens.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Have to use yres so message at some resolutions are kinda small
Fonts size and position weren't updating properly on screen size change

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #454

### CODE REVIEW

**Review by brysondev — DISMISSED** [review]

**Comment by AdamTadeusz** [comment]
@brysondev im sorry ;(

**Review by brysondev — DISMISSED** [review]

**Comment by AdamTadeusz** [comment]
this is driving me nuts im going through it again and resolutions where the central message was fitting nicely now don't

**Comment by brysondev** [comment]
Im being TROLLED I hate vgui

**Review by brysondev — APPROVED** [review]
gamemode NAN my favorite

**Review by nullsystem — APPROVED** [review]

**Pull request merged**
