### PR TITLE
Sprinting in water, crouch sprinting, speeds touchup

### LINKED ISSUE #435: [BUG] Can't sprint and crouch at the same time while bhopping (can in OG)
### Build Info

20240629_321f139

### Description

In OG NT, I can sprint and crouch at the same time while bhopping, which allows me to use the recon boost jump while still crouch bhopping. In NT;RE, I can't.

### To Reproduce

1. Join as a Recon
2. Do a boost jump (at the end Shift (sprint) is unpressed)
3. Start crouch bhopping around
4. Start to hold Shift (sprint) while still holding Ctrl (crouching)
5. Can't sprint, can't do another boost jump while still crouch bhopping

### Expected behavior

I can still be in the sprint state while crouch bhopping around, which allows me to do another boost jump without breaking my crouch bhop.

### Actual behavior

Can't, have to stop crouch bhopping and instead do normal bhopping, so that I can enter the sprint state and do another boost jump.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

_No response_

### LINKED ISSUE #563: Can't sprint in water
### Build Info

yupeee

### Description

In the original you can initiate a sprint when submerged

### To Reproduce

visit breakwater
jump in the water try to sprint

### Expected behavior

Can sprint

### Actual behavior

Cannot sprint

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

11

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #563
- fixes #435

### CODE REVIEW

**Review by Rainyan — COMMENTED** [review]
Seems good, but could you also adjust air speed while sprinting? In OG, you can "sprint" whilst airborne (i.e. the weapon lowers into the sprinting position), but you don't gain any speed. Same thing with sprinting whilst noclipping around, which is probably the easiest way to test this. Currently, you lose speed if sprinting while noclip flying, but sprint should have no effect on the air speed.

**Comment by AdamTadeusz** [comment]
I removed some unnecessary code too

**Review by Rainyan — DISMISSED** [review]
Tentative approve if we can't get into agreement over the sprint+move vs. move+sprint input handling.

Parity nit: sprinting while noclipping at full speed should not affect velocity (`cl_showpos`) but it does.

**Comment by AdamTadeusz** [comment]
> Tentative approve if we can't get into agreement over the sprint+move vs. move+sprint input handling.
> 
> Parity nit: sprinting while noclipping at full speed should not affect velocity (`cl_showpos`) but it does.

I can add shift -> move key sprinting

**Review by Rainyan — APPROVED** [review]

**Review by brysondev — APPROVED** [review]

**Pull request merged**
