### PR TITLE
Tony Sergi fixes integrations part 2 - networked animations

### LINKED ISSUE #121: Movement is correctly predicted/interpolated between client and server

### LINKED ISSUE #432: [BUG] Needs testing! - Players are flailing about erratically in third person, for some reason
### Build Info

20240629_321f139

### Description

For some reason, sometimes, players are faliling about erratically out in third person. Their animations are just broken, some players' anims aren't though.

### To Reproduce

1. Join multiplayer game
2. Look at a player near you
3. Sometimes their animations are broken and they are all erratic

### Expected behavior

Their animations are fine

### Actual behavior

They're erratic and glitched

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

Needs better testing + a recording, but other people during the playtest (2024-06-29) also noted this bug.

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Adds Tony Sergi's multiplayer_animstate.

Decided to drop neo_playeranimstate, hl2mp_playeranimstate does not differ that much from what we need for the neo player, but can revert it and multiplayer_animstate and put all the changes into neo_playeranimstate instead.

For the reviewers, unless you do not trust Tony Sergi's changes, I suggest clicking on the commit that he authored and marking all the changes there as read separately, should cut down on the amount of changes needed to be reviewed significantly.

[Edit] actually it seems that commit also contains my conflict resolutions so that won't work :(.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #121
- fixes #432

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
Still need to do some cleanup, should probably repurpose the old neo_playeranimstate to now includde the changes in hl2mp_playeranimstate and multiplayer_playeranimstate

**Review by brysondev — COMMENTED** [review]
lgtm but I'd like a proper test with lag compensation. EU host and we run through all the animations.

fakelag be damned I wanna see this forreal

**Comment by brysondev** [comment]
Still some animation looping issues with assault's head and grenade idle animations appear to be playing faster than they should.

**Review by brysondev — DISMISSED** [review]

**Review by Masterkatze — DISMISSED** [review]

**Review by brysondev — APPROVED** [review]
👍

**Review by Masterkatze — APPROVED** [review]

**Pull request merged**
