### PR TITLE
Update the bug report template

### PR DESCRIPTION
**Pull request by blaberry**
rephrased some stuff and changed the label used for reports to an original one.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #
- related #

### CODE REVIEW

**Comment by nullsystem** [comment]
I still object with the requirement of "desired state" in a bug report title. From the perspective of an outsider who just comes here and files a bug report, it's typical for the title to be written as a "the current state" like how other projects allows/typical done (can just pick out chromium, firefox, etc...) and this "Make sure..." text could even easily be glossed over.

**Review by Rainyan — DISMISSED** [review]

**Comment by blaberry** [comment]
I'm not sure I understand the second approach you recommend, does "use either should or should not phrasing" not fulfill "have a guideline for both style of title"? @nullsystem

**Comment by nullsystem** [comment]
@blaberry It's about "desired" vs "current" state of title phrasing

**Comment by blaberry** [comment]
Right, then we run into the issue we discussed at length over chat, where some items are desired state, some are not, and the mishmash of both will most likely turn out much harder to read than what's on offer in this PR

**Comment by nullsystem** [comment]
@blaberry There's an important distinction between a bug, change request (opinionated, current state isn't a bug), and feature request. There shouldn't be a blanket all of those have same "desired" state titles, and what on offer currently also gives a clearer distinction with the "[BUG] " title prefix even. The "desired" state titles are natural gravitation for change/feature requests, but as I've put it, the "current" state titles are natural gravitation for bug reports. It's not really a case of random some are/some are not thing, it's that there are distinction that issues titles written for bugs are done differently to change/feature requests.

**Comment by blaberry** [comment]
Alright so two different topics:

using a tag in the title: labels in Github are meant to categorize issues for easier filtering and searching. "[BUG]" in the title achieves a similar purpose, but it clutters the title and reduces readability. I added a new label to make this clearer. We can also add a label for FRs.

title formatting: I'll revert the title format instructions to how it was before since we can't find consensus on this.

**Review by nullsystem — CHANGES_REQUESTED** [review]
> There is a problem with this template
> 
> title must be of type String and cannot be empty.

https://github.com/NeotokyoRebuild/neo/blob/8844696f3dcda86a6ecea68444d759511c8ccdcd/.github/ISSUE_TEMPLATE/bug_report.yml

Removal of `[BUG]` feels like less clear on separate of bugs vs others but whatever.

**Review by nullsystem — APPROVED** [review]

**Review by Rainyan — APPROVED** [review]

**Pull request merged**
