### PR TITLE
Spec fixes - Lean 3p spec fix, POI mode filtered out

### LINKED ISSUE #418: [BUG] Dying whilst leaning results in an angled spectator camera when spectating in third person view or freecam
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

When you die whilst you are angled, the spectator camera inherits the lean angle, which results in both the freecam and third person spec being angled. This does not affect the first person spectating.

### To Reproduce

1. Be leaning
2. Get killed
3. Go to spectate, be in any other spectator mode other than first person spec, either third person spec or freecam

### Expected behavior

Spectator camera should not be angled

### Actual behavior

Spectator camera is angled

### Operating System

- [X] Windows
- [x] Linux

### Version/Distro

Windows 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### LINKED ISSUE #451: There shouldn't be an extra observer mode between third person and free cam
### Build Info

20240629_321f139

### Description

When cycling through the spectator modes with space there's an extra mode between third person and free cam.

### To Reproduce

Spectate another player. Press space to cycle through the modes.

### Expected behavior

The modes should go from first person -> third person -> free cam -> first person.

### Actual behavior

There's an extra mode after third person that behaves like third person but the hud is slightly different.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* Now unleans/not leans on death
* POI mode skipped over to next/prev enum

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #418
* fixes #451

### CODE REVIEW

**Review by VantoNortim — APPROVED** [review]

**Comment by AdamTadeusz** [comment]
I can't seem to replicate the original problem on master now xD

**Comment by nullsystem** [comment]
@AdamTadeusz If it helps, setting to use toggle lean instead of hold leans makes it easier to replicate the issue (and of course make sure mp_forcecamera is set to 0)

**Review by AdamTadeusz — APPROVED** [review]
On an unrelated note, a lot of stuff in prethink and postthink probably doesn't have to be done if the player is dead

**Comment by nullsystem** [comment]
@AdamTadeusz Yeah, could look over that at another time.

**Pull request merged**
