### PR TITLE
Tachi and Milso can no longer shoot underwater, water now protects from bullets

### LINKED ISSUE #565: [PARITY] Certain weapons can(not) shoot underwater
### Build Info

20240803_273dbf3

### Description

Certain guns that should be able to shoot underwater in OGNT are not able to be shot underwater.

In OGNT, those guns would be all of the secondaries (Tachi, Milso, Kyla), ZRC, ZRS and SRS.

In NTRE (on the 7.1 version), only guns that can be shot underwater are the Tachi and Milso.

### To Reproduce

1. Join game
2. Go underwater
3. Shoot gun

### Expected behavior

Guns that should be able to shoot underwater fire

### Actual behavior

Guns do not fire

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Personally, I think this is one of those parity things that could be improved right form the start, maybe just make all of the weapons being able to shoot underwater post parity release? I dont know what grey and co were cooking up when they made the guns, but it is a bit nonsensical that 90% of the guns dont fire underwater

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

https://github.com/NeotokyoRebuild/neo/discussions/625

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #565

### CODE REVIEW

**Review by Masterkatze — APPROVED** [review]

**Comment by Rainyan** [comment]
Is water protecting players from bullets parity behaviour? If not, have we reached consensus on this being what we want to happen?

**Comment by kassibuss** [comment]
It was (unanimously) decided by Zwia that none of the guns should shoot underwater. Considering majority of them don't and OGNT behavior is as wacky, I do not mind the change. Though we probably should have discussed it.

**Comment by AdamTadeusz** [comment]
I thought it would add an interesting depth to the game, also the guns that are able to shoot underwater in the original are a bit random, also nobody seemed to care

**Comment by AdamTadeusz** [comment]
Now knife is a little more viable on maps with a lot of water, and theres a reason against picking support on maps with a lot of water (since they don't have a knife)

**Review by brysondev — APPROVED** [review]

**Pull request merged**
