### PR TITLE
Replace root menu and settings

### LINKED ISSUE #542: [FEATURE] Replace the root menu and settings
**Current active PR: #539**

### Description

Source SDK 2013 can replace the root menu and isn't stuck to the limited customization of the default VGUI main menu. The first step is to override that menu and implement most of settings.

### Proposed Solution

The plan in stages:
1. Completely new UI overriding the root menu, implement most of settings with totally custom paint/key/mouse handling, keyboard navigation
2. Then, implement create-server and server browser into custom override UI
3. Then, support gamepad, unique settings for it and menu navigation
4. Then, implement spray settings, with custom filesystem browser and PNG+JPG conversion

Stage 2-4 will be done as separate issues + PR.

### Alternatives Considered

The current settings menu is rather limited in terms of customization, has a few settings widgets we can't fix/omit, and works poorly with gamepad controls.

### Additional Context
Replaces #64

### PR DESCRIPTION
**Pull request by nullsystem**
## Description
Override the root menu and replace it with our own. This allows for full customization unrestricted by whatever was given before. This first stage is just to replace the root main menu, and implement/replace settings. The other panel windows for the time being are left as they are.

### DONE
- [x] Root main menu replacement
- [x] Multiplayer, keybinds, mouse, audio, video settings
- [x] Keyboard navigation, root + settings
- [x] All custom UI, not using standard VGUI widget/controls as it's better to just deal with the input and paint ourselves
- [x] Download settings
- [x] Revert some standard VGUI panel changes as they're no longer used
- [x] Modified indicator, popup on back button, reset
- [x] Proper UI scaling on resolution
- [x] Voice/microphone tester
- [x] Some bit of reorganization on root menu styling/put more Steam-related stuff and news panel
- [x] Some bit of minor source code cleanup/refactor, better variable names
- [x] Compiles on both Windows and Linux

### As separate PRs
- Create server panel (possible via series of commands)
- Join server + server browser panel (possible via API)
- Gamepad navigation and settings (Gamepad section of keycode, ISteamController)
- Sprays settings (stb_image.h -> IVTFTexture -> filesystem, custom filepicker)

## Toolchain
- Windows MSVC VS2022
- Linux GCC Distro Native Arch/GCC 14.1.1

## Example screenshot
Settings - Multiplayer tab
2024-08-03T132157_screen

## Linked Issues
* fixes #542
* related #553

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
You're missing audio button feedback

image
image

https://github.com/user-attachments/assets/2979867f-76e2-4283-aaa8-05af042bbe1a

**Comment by nullsystem** [comment]
@AdamTadeusz I didn't bother with sound but I'll add them in just for root now. Won't do it for settings/sub-panels mostly cause original panels didn't either and just sounds kinda annoying.

**Comment by AdamTadeusz** [comment]
> @AdamTadeusz I didn't bother with sound but I'll add them in just for root now. Won't do it for settings/sub-panels mostly cause original panels didn't either and just sounds kinda annoying.

Nothing compares to ending a neotokyo sesh, hearing the buttonclickrelease.wav as the screen clears to nothing but the Do you wish to stop playing now? prompt, finally hearing out.wav cut out as you confirm

**Comment by AdamTadeusz** [comment]
I have a few other problems like text input being disabled when you move the mouse off of the field that you're entering text into, and there being no drop downs making changing resolution for example very tedious, but I guess for a first pass this is fine.

Also I suspect we will be getting a lot of complaints about text readability in the menu now.

**Review by AdamTadeusz — APPROVED** [review]

**Comment by nullsystem** [comment]
@AdamTadeusz Resolution probably more like split by aspect ratio like in original. But anyway lots in here already and mostly to prove root/settings replacement possibility. Refinements like such and maybe EX: HUD animations will come later anyway.

**Comment by nullsystem** [comment]
Superceeded by #554
Reason: The GUI API design has changed drasticly, so it's not much worth doing a code review on an API that been discarded and redone already.

**Pull request closed without merging**
