### PR TITLE
Center Text - Fix size and alias setting not being applied properly

### LINKED ISSUE #505: Center text size/alias not applied properly
### Build Info

20240712_a120e97

### Description

The font settings regarding sizing and aliasing option haven't been applied properly and could look like as if the font went "bigger" and looking unaliased on the 2nd map/match.

### To Reproduce

1. Create server -> Enter server
2. See the center font to see "initial font" (too small)
3. Then disconnect and do: Create server -> Enter server again
4. See the center font to see it went bigger but no alias

### Expected behavior

Center font being large size and have alias applied

### Actual behavior

Initially too small, then re-corrects size but alias not applied

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch Linux

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Initially, the font is too small (on first match):
2024-07-12T232112_screen
Then reload again to second match, and the font size is fine, but the alias option isn't applied:
2024-07-12T232021_screen

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* Probably to due with how it create/destroy this class
* Basically the font should be large and aliased. Before it was only one or the other.

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #505

### CODE REVIEW

**Review by VantoNortim — APPROVED** [review]
There are no jaggies and text is big.

**Review by brysondev — DISMISSED** [review]
nt_dimensions_test0000

lgtm

**Comment by nullsystem** [comment]
@brysondev The center text as in the large middle of the screen one that pops up and out, not the small one on the top.

**Comment by brysondev** [comment]
Yes sorry that screenshot didnt include the text. But it still looked good on my end when it appeared.

**Review by brysondev — APPROVED** [review]
nt_dimensions_test0004

lgtm

**Pull request merged**
