### PR TITLE
Kill feed - Change to neuropol2 font, white color separator

### LINKED ISSUE #442: Assists in killfeed should have a clearer separator
### Build Info

20240629_321f139

### Description

The current separator (some sort of minus sign in a circle?) has the same color as the killer which makes the names blend together. The text color should be white and probably use a regular +.

### To Reproduce

Need one player to hurt an enemy 50+ damage, and then have another player make the killing blow.

### Expected behavior

I can tell who's the killer and who's giving the assist.

### Actual behavior

The kill feed is a mess.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* OGNT killfeed font is neuropol2
* Removed unneeded ClientScheme_KillFeed.res
* Refactor a bit to just use the string directly

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #442

## Screenshot
killfeedwassistneuropol

### CODE REVIEW

**Review by AdamTadeusz — CHANGES_REQUESTED** [review]
image

My name is slightly cut off at the top with the new font, regardless of aspect ratio

(Edit) unless thats just the font

**Review by AdamTadeusz — DISMISSED** [review]

**Review by AdamTadeusz — APPROVED** [review]

**Review by brysondev — APPROVED** [review]
lgtm

**Comment by Agiel** [comment]
Not going to stop this PR but we should migrate back to using ClientScheme.res instead of ClientScheme_Neo.res

**Comment by nullsystem** [comment]
> Not going to stop this PR but we should migrate back to using ClientScheme.res instead of ClientScheme_Neo.res

Create new GH issue: #515

**Pull request merged**
