### PR TITLE
Grenade drawback fix

### LINKED ISSUE #535: [BUG] [Parity] Tapping the mouse1 button whilst having a grenade should not instantly throw the grenade
### Build Info

20240801_9d04458

### Description

In the original Neotokyo, when you tap your attack button, the animation for pulling the ring and throwing the grenade gets played. Currently, in the rebuild, the player instantly throws the grenade instead of going through the animation.

### To Reproduce

1. Join/launch a server
2. Pick a team
3. Pick assault
4. Equip grenade and tap M1 (or whatever the player has +attack bound to)

### Expected behavior

The player's character should pull the ring and then throw the grenade.

### Actual behavior

The player's character throws the grenade instantly whilst skipping the animations.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

MSVC 19.40.33812.0

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Toolchain

- Windows MSVC VS2022\

## Linked Issues

- fixes #535

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
#545 Should fix not being able to switch to another grenade of the same type once exhausting current grenade

**Comment by AdamTadeusz** [comment]
I measured the time from pressing a button to the grenade being thrown to be 0.42 as opposed to the 0.5 defined currently, but 0.5 results in the grenade being thrown much closer to the hand from the viewmodel throwing animation coming into view, so it looks much better this way in my opinion

**Comment by AdamTadeusz** [comment]
Just noticed the throwing animation does not fully play for the first smokegrenade

**Review by brysondev — APPROVED** [review]
LGTM. I can finally throw frags without my arms detatching :)

**Review by nullsystem — APPROVED** [review]

**Pull request merged**
