### PR TITLE
Scoreboard - Get_Score -> GetRoundsWon

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* Otherwise you'll get a "score" that's based on kills, not team round wins
* Long term solution could to change how that score works but for now this is fine

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

### CODE REVIEW

**Review by Rainyan — APPROVED** [review]

**Comment by Agiel** [comment]
Isn't it better to change how Get_Score works? I kinda assumed it already did the right thing. I mean if we're going to have a switch on game mode and everything I think it's the wrong place to put it in the scoreboard class.

**Comment by Rainyan** [comment]
@Agiel As these are declared together in the base class:
```cpp
	virtual int		Get_Score( void );
	virtual int		Get_Deaths( void );
	virtual int		Get_Ping( void );
```
I'm assuming "score" here is basically a misnomer for "frags"/"XP"/whatever yardstick of individual player performance, tallied up for that whole team.

But I guess we could override the base team, and check NEO rules for whether it's CTG, etc etc, if we wanted to do this "proper".

Although then we'd have both `GetRoundsWon` and a virtual overridden `Get_Score` doing the same thing for that class.

**Comment by AdamTadeusz** [comment]
The server side Team class doesn't seem to offer that much help either,
```
//------------------------------------------------------------------------------------------------------------------
// SCORING
//-----------------------------------------------------------------------------
// Purpose: Add / Remove score for this team
//-----------------------------------------------------------------------------
void CTeam::AddScore( int iScore )
{
	m_iScore += iScore;
}

void CTeam::SetScore( int iScore )
{
	m_iScore = iScore;
}
```
Maybe just include a NEO HACK comment so we can find this easily later?

**Comment by nullsystem** [comment]
I think rain's suggestion of something like a `CNEOTeam` that can deal with more gamemodes would be the way to go. But for now `GetRoundsWon` will do, which is already utilized in multiple places anyway.

**Review by AdamTadeusz — APPROVED** [review]

**Comment by nullsystem** [comment]
Superseded by #410

**Pull request closed without merging**
