### PR TITLE
Update README.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by xedmain**
- Added server instructions for linux server ops
- Additional corrections/edits
- Removed TOC in README.md and CONTRIBUTING.md because there's a button for that on GitHub

### CODE REVIEW

**Review by Rainyan — APPROVED** [review]

**Comment by Rainyan** [comment]
This makes the README table of contents somewhat outdated though. But I'm not sure if we wanna keep maintaining that listing by hand, as it seems the new GitHub web UI has a "Headings" tool in the top-right hamburger menu already:

toc

Alternatively could set up some GitHub action that rebuilds the ToC for changes to README.md in master.

**Comment by Rainyan** [comment]
> I could manually edit the ToC if needed, but I decided that there would be too many subheadings or sth imo, would you want it to have subheadings for Server Ops and Testers/Devs?

I'm ok with keeping the current headings as-is for now. @nullsystem do you have any opinions on this?

**Comment by nullsystem** [comment]
@Rainyan @xedmain I'm tempted to just say remove the manual listing and just direct people to use that button for table of content. Admittedly I didn't realize it's a thing but it's automatic and interactive. Also change it for CONTRIBUTING.md.

**Comment by nullsystem** [comment]
> Sure, should I also edit CONTRIBUTING.md as well?

@xedmain Yes

**Review by nullsystem — APPROVED** [review]

**Review by Rainyan — APPROVED** [review]
Thank you!

**Review by nullsystem — APPROVED** [review]

**Pull request merged**
