### PR TITLE
Replace neo_hud_elements to huds managing themselves

### LINKED ISSUE #332: Refactor neo_hud_elements - memory management
Just to remind myself to follow up from: https://github.com/NeotokyoRebuild/neo/pull/326#discussion_r1623638029

Basically let the global HUD element handle the memory instead of neo_hud_elements. Done via `DECLARE_HUDELEMENT` and fetched via `GET_HUDELEMENT` instead.

### PR DESCRIPTION
**Pull request by nullsystem**
* Basically let the global HUD element handle the memory instead of `neo_hud_elements`. Done via `DECLARE_HUDELEMENT/DECLARE_NAMED_HUDELEMENT` and fetched via `GET_HUDELEMENT/GET_NAMED_HUDELEMENT` instead.
* Removed `neo_hud_elements` entirely
* Make sure to check: ammo, compass, friend markers, ghost beacons/markers, health/AUX/Therm, round state, worldpos marker, are still fine
* fixes #332

### CODE REVIEW

**Review by Rainyan — APPROVED** [review]
LGTM

**Review by AdamTadeusz — DISMISSED** [review]

**Comment by nullsystem** [comment]
Just a rebase done to fix merge conflicts.

**Comment by AdamTadeusz** [comment]
> Just a rebase done to fix merge conflicts.

Are you sure? git diff shows a lot of changes and the date of the latest commit on this branch is now from 10 days ago

**Comment by AdamTadeusz** [comment]
Shit

**Review by Rainyan — APPROVED** [review]

**Comment by nullsystem** [comment]
> > Just a rebase done to fix merge conflicts.
> 
> Are you sure? git diff shows a lot of changes and the date of the latest commit on this branch is now from 10 days ago

@AdamTadeusz I think you're looking at the local, not remote branch/haven't updated it to match remote yet.

**Review by AdamTadeusz — APPROVED** [review]

**Pull request merged**
